### ISSUE TITLE
Pic

### ISSUE THREAD

**Issue by mbrevda** [Strooom/SmartTherm#1]
Can you possible show a picture of how this is connected to the boiler? Thanks!

**Comment by Strooom** [comment]
Pin 1 = 24V
Pin 2 = Control : From thermostat or MCU to Junkers
Pin 4 = Ground

![IMG_3360](https://user-images.githubusercontent.com/16426853/103099966-ceed2080-4610-11eb-8da1-1faad27b3f82.JPG)

**Comment by mbrevda** [comment]
Thanks! Ended up going with a Shelly as illustrated [here](https://blog.pattyland.de/2019/12/01/alte-junkers-gastherme-smart-machen/), along with thermostats in every room. I guess that means I'm not utilizing modulation. Wonder what the real-world implications are...

**Comment by nagyrobi** [comment]
> Wonder what the real-world implications are...

Less efficiency thus higher energy consumption...

**Comment by mbrevda** [comment]
> Less efficiency thus higher energy consumption...

Still wonder about this: heating up _faster_ vs heating for _longer_ (albeit at lower power) - how do we know which one is really cheaper in the long run?
