### ISSUE TITLE
MQTT 

### ISSUE THREAD

**Issue by fir3drag0n** [Strooom/SmartTherm#3]
Is there a new firmware for v2 to control it by MQTT?

I would like to integrate it in iobroker.

**Comment by jensweimann** [comment]
See PR: https://github.com/Strooom/SmartTherm/pull/4

**Comment by Strooom** [comment]
I am currently not working on this project - feel free to build the hardware and put whatever ESP8266 (or even ESP32) software on it. For my application, it is doing its job and I have too many other developments taking up all of my time.

That being said : my original development is using Blynk, but this application has had a complete makeover, so the one I am using is obsolete. So, some day I could rewrite the software to work with some other cloud solution, eg the Arduino cloud.

Any developers interested on taking the development further : I can add you to the team and then you can take ownership.

Thank you all!
